#!/usr/bin/env bash
# script to install nginx on web server

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html

sed -i 's/listen\s*80/listen 0.0.0.0:80/' /etc/nginx/sites-available/default

service nginx restart
